# Test training

In [1]:
from src.dataset_utils import Dataset
from src.model import TFModel

In [2]:
train = True

In [3]:
#prepare the training data
print('now creating dataset'.center(60, '-'))
data = Dataset(train)
data.prepare_training_data()


--------------------now creating dataset--------------------
-------------------splitting the dataset--------------------
------------------make tensorflow dataset-------------------
--------------------adapting vectorizer---------------------


In [4]:
#train the model
model = TFModel()
model.train_and_eval(data.train_df, data.val_df)

---------------------creating the model---------------------
---------------------training the model---------------------
Epoch 1/10
6647/6650 [============================>.] - ETA: 0s - loss: 0.8821 - acc: 0.5825
Epoch 1: val_acc improved from -inf to 0.65725, saving model to model/lstm_model\cp.ckpt
6650/6650 [==============================] - 99s 14ms/step - loss: 0.8820 - acc: 0.5827 - val_loss: 0.7990 - val_acc: 0.6572
Epoch 2/10
6649/6650 [============================>.] - ETA: 0s - loss: 0.5721 - acc: 0.7624
Epoch 2: val_acc did not improve from 0.65725
6650/6650 [==============================] - 92s 14ms/step - loss: 0.5722 - acc: 0.7623 - val_loss: 0.8170 - val_acc: 0.6470
Epoch 3/10
6649/6650 [============================>.] - ETA: 0s - loss: 0.3169 - acc: 0.8806
Epoch 3: val_acc did not improve from 0.65725
6650/6650 [==============================] - 92s 14ms/step - loss: 0.3168 - acc: 0.8806 - val_loss: 0.9134 - val_acc: 0.6452
Epoch 4/10
6648/6650 [=====================

# Test Inference

In [2]:
train = False

In [3]:
#prepare the inference data
print('now creating dataset'.center(60, '-'))
data = Dataset(train)
data.prepare_inference_data()

--------------------now creating dataset--------------------


In [4]:
model = TFModel()
y = model.inference(data.df)

500/500 [==============================] - 3s 3ms/step


In [6]:
import numpy as np

In [7]:
np.argmax(y, axis=1)

array([2, 0, 0, 2, 2, 1, 0, 1, 2, 2, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 2,
       0, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 2, 0, 0, 2, 2, 2, 0, 2, 2,
       0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 0, 0,
       2, 2, 0, 2, 1, 1, 0, 2, 2, 0, 2, 0, 2, 2, 1, 2, 1, 2, 2, 0, 0, 1,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2,
       0, 2, 0, 2, 2, 1, 2, 2, 2, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 2, 0, 2,
       2, 1, 0, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 2, 0, 0, 2, 0, 1, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 0, 0, 0, 2, 1,
       2, 1, 2, 1, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0,
       1, 1, 0, 1, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 1, 0, 0,
       0, 0, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 1, 2,
       1, 0, 1, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2,

In [13]:
model.model.predict(data.df)

500/500 [==============================] - 2s 3ms/step


array([[0.00754483, 0.11933167, 0.87312347],
       [0.6369501 , 0.23918152, 0.12386839],
       [0.43197018, 0.3414396 , 0.2265902 ],
       ...,
       [0.5837515 , 0.26018122, 0.15606733],
       [0.05568497, 0.22663596, 0.7176791 ],
       [0.73668855, 0.1678365 , 0.09547488]], dtype=float32)

In [12]:
for row in data.df.take(3):
    print(row)

tf.Tensor(
[[  52  279 1047 1958  277  102  144    7    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]], shape=(1, 100), dtype=int64)
tf.Tensor(
[[ 347   47 4411  571  413  125    7    3   14 1923 2135   41  157 4308
   130    5  610 1780   14    2  242 1761 1742  328    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    